#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Robotics Tutorials  # The title of the book. Will be placed in the left navbar.
author                      : University of Southampton  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : img/oplab_logo.png  # A path to the book logo

# Global settings
only_build_toc_files        : false
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "tutorials/*/*ipynb", "**.pytest_cache", "solutions/assignment*/*", "autograded", "submitted", "feedback"]

execute:
  timeout                   : 120    # The maximum time (in seconds) each notebook cell is allowed to run.

parse:
  myst_enable_extensions:
    - colon_fence
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - tasklist

# Online stuff
repository:
  url                       : https://github.com/ocean-perception/robotics_tutorials
  path_to_book              : robotics_tutorials
  branch                    : main

launch_buttons:
  notebook_interface        : jupyterlab
  binderhub_url             : https://mybinder.org
  colab_url                 : https://colab.research.google.com

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

